name: terraform workflows
on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  Scan:
    if: ${{ github.event_name == 'push' }}
    uses: cumberland-cloud/workflows/.github/workflows/tf-scan.yaml@master
  Lint:
    if: ${{ github.event_name == 'push' }}
    uses: cumberland-cloud/workflows/.github/workflows/tf-lint.yaml@master
  Docs:
    if: ${{ github.event_name == 'pull_request' }}
    uses: cumberland-cloud/workflows/.github/workflows/gh-pages.yaml@master
    with:
      TFDOCS: true
  Release:
    uses: cumberland-cloud/workflows/.github/workflows/tf-release.yaml@master
    needs: [ Scan, Lint ]
    secrets: inherit
    with:
      TF_APPLY: false